name: nummo
description: "A simple, elegant personal finance tracker android app designed for speed and clarity. Track every Rupee with ease."
publish_to: 'none'
version: 1.1.9

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  file_picker: ^8.1.7
  intl: ^0.20.3
  fl_chart: ^1.2.0
  local_auth: ^3.0.2
  flutter_svg: ^2.3.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.1
  pdf: 3.11.1
  excel: 4.0.6
  csv: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - logo/nummo.png
    - logo/nummo.svg
    - logo/memoji.png
    - logo/website.png
    - web/favicon.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "logo/nummo.png"
  adaptive_icon_background: "#0F1117"
  adaptive_icon_foreground: "logo/AppIcons/android/adaptive-foreground.png"
  web:
    generate: true
    image_path: "logo/nummo.png"
    background_color: "#0F1117"
    theme_color: "#0F1117"

